config/routes.rb
Rails.application.routes.draw do
  root "people#index"
  resources :people
end

app/models/person.rb
class Person < ActiveRecord::Base
  GENDERS = [ "male", "female"]

  has_attached_file :picture,
                    url: "/assests/pictures/:id/:style/:basename.:extension",
                    path: ":rails_root/public/assests/pictures/:id/:style/:basename.:extension",
                    default_url: "/assests/pictures/missing.png"

  validates :first_name,  presence: true, length: { maximum: 75 }
  validates :last_name,   presence: true, length: { maximum: 75 }
  validates :email,       presence: true, uniqueness: true, length: { maximum: 254 },
                          format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :bio,         length: {maximum: 500}
  validates :gender,      presence: true, inclusion: {in: GENDERS}
  validates :birthdate,   presence: true
  validate :is_valid_birthdate?
  validates_attachment :picture, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
  validates_with AttachmentSizeValidator, attributes: :picture, less_than: 5.megabytes

  scope :order_by_full_name, ->{order("first_name, last_name")}

  # Public: Join of first_name and last_name to return the full name of a person.
  #
  # Returns the full name String
  def full_name
    "#{first_name} #{last_name}"
  end

  # Public: Get the current time and the date of birth of the person and calculate the age
  #
  # Examples
  #
  #   Person.first.age
  #   # => 24
  #
  # Returns the age of a person Integer.
  def age
    now = Time.current.utc.to_date
    now.year - birthdate.year - (birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  private
    # Private: Add error if the birthdate is greater then current date
    #
    # Returns the duplicated String.
    def is_valid_birthdate?
      errors.add(:birthdate, 'should be in the past') unless self.birthdate && self.birthdate <= Date.current
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
# This pattern in controllers is following the guides of Growing Rails Application Book
# this way the controller is as DRY as posible
class PeopleController < ApplicationController
  def index
    load_people
  end

  def show
    load_person
  end

  def new
    build_person
  end

  def create
    build_person
    save_person(perform_email: true) or render :new
  end

  def edit
    load_person
    build_person
  end

  def update
    load_person
    build_person
    save_person or render :edit
  end

  def destroy
    load_person
    @person.destroy
    DeletedPersonEmailJob.perform_later(name: @person.full_name, email: @person.email)
    flash[:notice] = "Person deleted successfuly"
    redirect_to people_path
  end

  private
    # Private: load the 'default' scope in an instace variable
    #
    # Returns the @people intance variable the 'default' scope
    # used on :index action
    def load_people
      @people = people_scope
    end

    # Private: Take care of load a person even if it is new or not
    #
    # Returns the @person intance variable for existing record with the 'default' scope
    # used on :show, :edit, :update, :destroy actions
    def load_person
      @person ||= people_scope.find(params[:id])
    end

    # Private: Take care of build a person even if it is new or not
    #
    # Returns the @person instance variable for existing or new record
    # to use in :new, :create, :edit, :update actions
    def build_person
      @person ||= people_scope.build
      @person.attributes = person_params
    end

    # Private: Take care of saving a person even if it is new or not
    #
    # Returns redirect to the person profile if saved correcty otherwise will show a flash with errors
    # used on :create and :update actions
    def save_person(perform_email: false)
      if @person.save
        flash[:notice] = "Person saved successfuly"
        NewPersonEmailJob.perform_later(@person.id) if perform_email
        redirect_to @person
      else
        flash[:error] = @person.errors.full_messages.to_sentence
        false
      end
    end

    # Private: Returns attributes that can be set through the update and create actions
    #
    # Returns Hash with the Person attributes or empty
    def person_params
      person_params = params[:person]
      person_params ? person_params.permit(:first_name, :last_name, :email, :bio, :gender, :job, :birthdate, :picture) : {}
    end

    # Private: Get the 'default' scope for this controller,
    #          over this scope all the queries will be executed
    #
    # Returns ActiveRecordRelation with the Person entries
    def people_scope
      Person.all.order_by_full_name
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "PeopleSystem"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    = render "shared/header"
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      = render "shared/footer"

app/views/people/_basic_information.html.haml
%table.table.table-user-information
  %tbody
    %tr
      %td First name:
      %td= person.first_name
    %tr
      %td Last name:
      %td= person.last_name
    %tr
      %td Email:
      %td= link_to person.email, "mailto:#{person.email}"
    %tr
      %td Job:
      %td= person.job.titleize
    %tr
      %td Birthdate:
      %td= person.birthdate
    %tr
      %td Age:
      %td= person.age
    %tr
      %td Bio
      %td= person.bio
    %tr
    %tr
      %td Gender
      %td= person.gender

app/views/people/_form.html.haml
%h2= @person.full_name
= form_for person, url: url, html: { multipart: true } do |f|
  %div.form-group
    = f.label :first_name
    = f.text_field :first_name, class: "form-control"
  %div.form-group
    = f.label :last_name
    = f.text_field :last_name, class: "form-control"
  %div.form-group
    = f.label :email
    = f.email_field :email, class: "form-control"
  %div.form-group
    = f.label :job
    = f.text_field :job, class: "form-control"
  %div.form-group
    = f.label :bio
    = f.text_area :bio, class: "form-control"
  %div.form-group
    = f.label :gender
    = f.select :gender, Person::GENDERS, class: "form-control"
  %div.form-group
    = f.label :birthdate
    = f.date_field :birthdate, class: "form-control"

  %div.form-group
    = f.file_field :picture

  = f.submit "Save", class: "btn btn-primary"
  = link_to "Cancel", person_path(person), class: "btn btn-default" unless person.new_record?

app/views/people/_person.html.haml
%tr
  %td
    = link_to person.full_name, person_path(person)
  %td
    = person.email
  %td
    = person.age
  %td
    =link_to "Delete", person_path(person), method: :delete, data: {confirm: "Are you sure you want to delete this person?"}, class: "btn btn-danger"
    = link_to "Edit", edit_person_path(person), class: "btn btn-primary"

app/views/people/edit.html.haml
- content_for :title do
  PeopleSystem - Edit a Person
= render "people/form", url: person_path(@person), person: @person

app/views/people/index.html.haml
- content_for :title do
  PeopleSystem - List of people

%table.table
  %caption
    List of people in the system
  %thead
    %tr
      %th first name - last name
      %th email
      %th age
      %th actions
    %tbody
      = render partial: "person", collection: @people, as: :person

app/views/people/new.html.haml
- content_for :title do
  PeopleSystem - New Person
= render "people/form", url: people_path, person: @person

app/views/people/show.html.haml
- content_for :title do
  PeopleSystem - Profile
.container-fluid
  .panel
    .panel-heading
      %h3.panel-title= @person.full_name
    .panel-body
      .row
        .col-md-3.col-lg-3
          = image_tag (@person.picture.url), class: "img img-circle img-responsive"
        .col-md-9.col-lg-9
          = render "people/basic_information", person: @person
          = link_to "Edit", edit_person_path(@person), class: "btn btn-primary"
          = link_to "Delete", person_path(@person), method: :delete, data: {confirm: "Are you sure you want to delete this person?"}, class: "btn btn-danger"
          = link_to "Cancel", people_path, class: "btn btn-default"

app/views/shared/_footer.html.haml
%footer
  %p © Company 2015

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to "PeopleSystem", root_path, class: "navbar-brand"
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li= link_to "People List", people_path
        %li= link_to "New Person", new_person_path